name: qr4cqa
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=39.0.1
  - cudatoolkit=11.3.1
  - ffmpeg=4.3
  - flit-core=3.6.0
  - freetype=2.12.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.4
  - intel-openmp=2021.4.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.4
  - nettle=3.7.3
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openh264=2.1.1
  - openssl=1.1.1t
  - pillow=9.4.0
  - pip=22.3.1
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.8.16
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - readline=8.2
  - requests=2.28.1
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.40.1
  - tk=8.6.12
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - typing_extensions=4.4.0
  - urllib3=1.26.14
  - wheel=0.38.4
  - xz=5.2.10
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - anyio==3.6.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - asttokens==2.2.1
    - async-timeout==4.0.2
    - attrs==22.2.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.2
    - bleach==6.0.0
    - bs4==0.0.1
    - click==8.0.4
    - comm==0.1.2
    - contourpy==1.0.7
    - cycler==0.11.0
    - datasets==2.10.1
    - debugpy==1.6.6
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dill==0.3.6
    - distlib==0.3.6
    - elementpath==4.0.1
    - executing==1.2.0
    - fastapi==0.92.0
    - fastjsonschema==2.16.3
    - filelock==3.9.0
    - fonttools==4.38.0
    - fqdn==1.5.1
    - frozenlist==1.3.3
    - fsspec==2023.1.0
    - grpcio==1.43.0
    - huggingface-hub==0.12.1
    - importlib-metadata==6.0.0
    - importlib-resources==5.12.0
    - ipykernel==6.21.3
    - ipython==8.11.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.4
    - isoduration==20.11.0
    - jedi==0.18.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - jupyter==1.0.0
    - jupyter-client==8.0.3
    - jupyter-console==6.6.3
    - jupyter-core==5.2.0
    - jupyter-events==0.6.3
    - jupyter-server==2.4.0
    - jupyter-server-terminals==0.4.4
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.5
    - kiwisolver==1.4.4
    - lxml==4.9.2
    - markupsafe==2.1.2
    - matplotlib==3.7.0
    - matplotlib-inline==0.1.6
    - mistune==2.0.5
    - msgpack==1.0.4
    - multidict==6.0.4
    - multiprocess==0.70.14
    - nbclassic==0.5.3
    - nbclient==0.7.2
    - nbconvert==7.2.9
    - nbformat==5.7.3
    - nest-asyncio==1.5.6
    - nltk==3.8.1
    - notebook==6.5.3
    - notebook-shim==0.2.2
    - opencv-python==4.6.0.66
    - packaging==23.0
    - pandas==1.5.3
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pkgutil-resolve-name==1.3.10
    - platformdirs==3.0.0
    - prometheus-client==0.16.0
    - prompt-toolkit==3.0.38
    - protobuf==3.20.3
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - py-vncorenlp==0.1.4
    - pyarrow==11.0.0
    - pydantic==1.10.5
    - pygments==2.14.0
    - pyjnius==1.4.2
    - pyparsing==3.0.9
    - pyrsistent==0.19.3
    - python-crfsuite==0.9.9
    - python-dateutil==2.8.2
    - python-json-logger==2.0.7
    - pytrends==4.9.0
    - pytz==2022.7.1
    - pyyaml==6.0
    - pyzmq==25.0.0
    - qtconsole==5.4.0
    - qtpy==2.3.0
    - ray==1.13.0
    - regex==2022.10.31
    - responses==0.18.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - sacremoses==0.0.53
    - scikit-learn==1.2.1
    - scipy==1.10.1
    - send2trash==1.8.0
    - sentencepiece==0.1.97
    - seqeval==1.2.2
    - sniffio==1.3.0
    - soupsieve==2.4
    - stack-data==0.6.2
    - starlette==0.25.0
    - terminado==0.17.1
    - threadpoolctl==3.1.0
    - tinycss2==1.2.1
    - tokenizers==0.13.2
    - tornado==6.2
    - tqdm==4.64.1
    - traitlets==5.9.0
    - underthesea==6.1.4
    - underthesea-core==1.0.0
    - uri-template==1.2.0
    - virtualenv==20.20.0
    - vncorenlp==1.0.3
    - wcwidth==0.2.6
    - webcolors==1.12
    - webencodings==0.5.1
    - websocket-client==1.5.1
    - widgetsnbextension==4.0.5
    - xxhash==3.2.0
    - yarl==1.8.2
    - zipp==3.15.0
